version: 2
jobs:
    build:
        working_directory: ~/work
        machine: true
        steps:
            - checkout
            - restore_cache:
                key: docker-base-{{ checksum "Dockerfile.base" }}
                path: ~/cache/base-image.tar
            - restore_cache:
                key: docker-pandoc-{{ checksum "Dockerfile.pandoc" }}
                path: ~/cache/pandoc-image.tar
            - restore_cache:
                key: docker-texlive-{{ checksum "Dockerfile.texlive" }}
                path: ~/cache/texlive-image.tar

            - run:
                name: load docker cache
                command: |
                    test -f ~/cache/base-image.tar && docker load -i ~/cache/base-image.tar
                    test -f ~/cache/pandoc-image.tar && docker load -i ~/cache/pandoc-image.tar
                    test -f ~/cache/texlive-image.tar && docker load -i ~/cache/texlive-image.tar
                    docker images odanado/book
            - run: docker build -f Dockerfile.base -t odanado/book:base --cache-from odanado/book:base .
            - run: docker build -f Dockerfile.pandoc -t odanado/book:pandoc --cache-from odanado/book:pandoc .
            - run: docker build -f Dockerfile.texlive -t odanado/book:texlive --cache-from odanado/book:texlive .

            - run:
                name: save docker cache
                command: |
                    mkdir -p ~/cache
                    docker save -o ~/cache/base-image.tar odanado/book:base 
                    docker save -o ~/cache/pandoc-image.tar odanado/book:pandoc 
                    docker save -o ~/cache/texlive-image.tar odanado/book:texlive 
                    docker images odanado/book

            - save_cache:
                key: docker-base-{{ checksum "Dockerfile.base" }}
                paths: ~/cache/base-image.tar
            - save_cache:
                key: docker-pandoc-{{ checksum "Dockerfile.pandoc" }}
                paths: ~/cache/pandoc-image.tar
            - save_cache:
                key: docker-texlive-{{ checksum "Dockerfile.texlive" }}
                paths: ~/cache/texlive-image.tar
            
            - run: make docker-all
            - store_artifacts:
                path: ~/work/main.pdf
            - save_cache:
                key: build-{{ checksum "~/work/main.pdf"}}
                paths: ~/work/build


    
    deploy-gh-pages:
        working_directory: ~/work/build
        machine: true
        steps:
            - restore_cache:
                key: build
            - run: git init .
            - run: git config --global user.name "circle ci"
            - run: git config --global user.email "odan3240@gmail.com"
            - run: git checkout -b gh-pages
            - run: git add *.html
            - run: git commit -m 'Update [ci skip]'
            - run: git push -f git@github.com:odanado/pandoc-sandbox.git gh-pages


workflows:
    version: 2
    flow:
        jobs:
            - build
            - deploy-gh-pages:
                requires:
                    - build
                filters:
                    branches:
                        only: master
