version: 2
jobs:
    build:
        working_directory: ~/work
        machine: true
        steps:
            - checkout
            - restore_cache:
                key: docker-{{ checksum "Dockerfile" }}
                path: ~/cache/image.tar

            - run: if test -d ~/cache; then docker load -i ~/cache/image.tar; fi
            - run: docker build -t odanado/pandoc .
            - run: mkdir -p ~/cache && docker save -o ~/cache/image.tar odanado/pandoc $(docker history -q odanado/pandoc | tail -n +2 | grep -v \<missing\> | tr '\n' ' ')

            - save_cache:
                key: docker-{{ checksum "Dockerfile" }}
                paths: ~/cache

    
    build-book:
        working_directory: ~/work
        machine: true
        steps:
            - checkout
            - restore_cache:
                key: docker-{{ checksum "Dockerfile" }}
                path: ~/cache

            - run: docker load -i ~/cache/image.tar
            - run: docker run --user=root --rm -it -v $PWD:/home/user/work -e NB_UID=`id -u` -e NB_GID=`id -g` odanado/pandoc run.sh make
            - run: docker run --user=root --rm -it -v $PWD:/home/user/work -e NB_UID=`id -u` -e NB_GID=`id -g` odanado/pandoc run.sh make html

            - store_artifacts:
                path: ~/work/main.pdf

workflows:
    version: 2
    flow:
        jobs:
            - build
            - build-book:
                requires:
                    - build 
